spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/article_guide
    username: syh2516
    password: Sung2516@

  jpa:
    hibernate:
      ddl-auto: update
